from __future__ import annotations

from typing import Protocol

from chronos.reminders.models import Reminder


class ReminderRepository(Protocol):
    def list(self) -> list[Reminder]: ...
    def get(self, reminder_id: str) -> Reminder | None: ...
    def save(self, reminder: Reminder) -> None: ...
    def delete(self, reminder_id: str) -> bool: ...
