"""Persistence and integration boundaries for Schedule."""

from __future__ import annotations

from datetime import date
from typing import Protocol

from chronos.schedule.models import FixedBlock, Plan, Task


class ScheduleRepository(Protocol):
    def list_tasks(self) -> list[Task]: ...
    def save_task(self, task: Task) -> None: ...
    def delete_task(self, task_id: str) -> bool: ...
    def get_task(self, task_id: str) -> Task | None: ...
    def list_fixed_blocks(self, target_date: date) -> list[FixedBlock]: ...
    def save_fixed_block(self, block: FixedBlock) -> None: ...
    def delete_fixed_block(self, block_id: str) -> bool: ...
    def next_plan_version(self, target_date: date) -> int: ...
    def save_plan(self, plan: Plan) -> None: ...
    def get_plan(self, plan_id: str) -> Plan | None: ...
    def latest_plan(self, target_date: date) -> Plan | None: ...
    def activate_plan(self, plan_id: str) -> Plan: ...
    def get_setting(self, key: str) -> str | None: ...
    def set_setting(self, key: str, value: str) -> None: ...


class ProposalRepository(Protocol):
    def save(self, proposal: dict[str, object]) -> dict[str, object]: ...
    def get(self, proposal_id: str) -> dict[str, object] | None: ...
    def list(self, limit: int = 100) -> list[dict[str, object]]: ...
